---
development: &defaults
  adapter: postgres
  database: budget_app
  username: maximlee
  password: budget_app_password
  # host: 127.0.0.1

test:
  <<: *defaults

production:
  <<: *defaults
  username: jetteim
