version: '2'
services:
  postgres:
    image: postgres:9.5
    restart: always
    environment:
       POSTGRES_PASSWORD: budget_app_password
       POSTGRES_USER: budget_app
       POSTGRES_DB: budget_app
    expose:
      - "5432"
  budgetapp:
    build: .
    restart: always
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      DATABASE_URL: "postgres://budget_app:budget_app_password@postgres/budget_app?sslmode=disable"
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_LOG_TO_STDOUT: "true"
    ports:
      - "3000:3000"
