source 'https://rubygems.org'

# Padrino supports Ruby version 1.9 and later
# ruby '2.4.2'

# Distribute your app as a gem
# gemspec

# Server requirements
# gem 'thin' # or mongrel
# gem 'trinidad', :platform => 'jruby'

# Optional JSON codec (faster performance)
# gem 'oj'

# Project requirements
gem 'rake'
gem 'thin'

# Component requirements
gem 'ohm', '~> 1.3.0'

# Test requirements

gem 'padrino-core'
gem 'padrino-gen'
