source 'https://rubygems.org'
# group :servers do
#   gem 'thin'
# end

# group :rake do
#   gem 'rake'
# end
#
group :telegram do
  gem 'telegramAPI'
  gem 'rest-client', ">= 2.0.1"
end

group :misc do
  gem 'colorize'
end
